[general]
live_config_reload = true

[window.dimensions]
columns = 84
lines = 27

[window]
title = "erm"
opacity = 1.0

[font]
size = 12

[font.normal]
family = "JetBrains Mono"

[terminal]
shell = "/usr/bin/fish"


[colors.primary]
background = "#ffffff"
foreground = "#000000"

[colors.normal]
black   = "#000000"
red     = "#000000"
green   = "#000000"
yellow   ="#000000"
blue    = "#000000"
magenta = "#000000"
cyan    = "#000000"
white   = "#000000"
